driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: fedora-25
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.3
    run_list: freebsd::portsnap
  - name: opensuse-13.2
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list: ntp::default
    attributes:
      ntp:
        sync_clock: true
        sync_hw_clock: true
